module.exports = [
  { path: "/" },
  { path: "/about" },
  { path: "/corporate" },
  { path: "/blog" },
  { path: "/news" },
  { path: "/faq" },
  { path: "/contact" },
  { path: "/privacy-policy" },
  { path: "/terms-conditions" },
  { path: "/return-refund" },
  { path: "/shipping-delivery" },
  { path: "/cart" },
  { path: "/wishlist" },
  { path: "/checkout" },
  { path: "/account" },
  { path: "/account/profile" },
  { path: "/account/orders" },
  { path: "/shop/premium" },
  { path: "/shop/promotion" },
];
